project:
  type: book

book:
  title: "Openscapes Team Compass"
  author: "Openscapes"
  site-url: https://openscapes.github.io/team-compass
  repo-url: https://github.com/openscapes/team-compass
  date: "6/2/2021"
  page-navigation: true
  sidebar:
    style: "docked"
    background: light
    search: true
    collapse-level: 2
  chapters:
    - index.md
# part: Getting Started
    - docs/getting_started/earthdata_login.md
    # - docs/getting_started/earthdata_login_test.md
    # - docs/getting_started/authentication.md
    # - docs/getting_started/netrc_file.md
    # - docs/getting_started/inline_authentication.md
# part: Backgound
#   - cloud_optimized_data_formats.md
# part: NASA Cloud Data Discovery
    - docs/practices/discovery.md
    - docs/code-of-conduct/code-of-conduct.md
    - docs/references.md

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: report
  epub:
    cover-image: openscapes_hex.png

