project:
  type: book

book:
  title: "Openscapes Team Compass"
  author: "Openscapes"
  site-url: https://openscapes.github.io/team-compass
  repo-url: https://github.com/openscapes/team-compass
  date: "6/2/2021"
  page-navigation: true
  sidebar:
    style: "docked"
    background: light
    search: true
    collapse-level: 2
  chapters:
    - index.md
# part: Getting Started
    - docs/practices/get-started.md
    - docs/champions/about.md
    - docs/code-of-conduct/code-of-conduct.md
    - docs/references.md

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: report
  epub:
    cover-image: openscapes_hex.png

