project:
  type: book
  output-dir: docs
  
book:
  title: "Openscapes Team Compass"
  author: "Openscapes"
  logo: openscapes_hex.png
  repo-url: https://github.com/openscapes/team-compass
  repo-actions: [edit, issue]
  sharing: [twitter]
  # date: "Last updated June 2021"
  # page-navigation: true
  # sidebar:
  #   style: "docked"
  #   background: light
  #   search: true
  #   collapse-level: 2
  chapters:
    - text: "Welcome"
      href: index.md  
    - part: practices/index.md
      chapters:
        - practices/code-of-conduct.md
    - part: "Champions Program"
      chapters:
        - champions/about.md
        - champions/operations.md
    - part: "Reference"
      chapters:
        - reference/inspiration.md

bibliography: references.bib

format:
  html:
    theme: cosmo
    # css: styles.css
    # toc: true # this adds the right-side "on this page" navigation
#     
# filters:
#   - filters/include-files.lua


