project:
  type: site
  output-dir: _site

execute:
  ipynb: false
  freeze: true
  
site:
  title: "Openscapes Approach Guide" 
  site-url: https://openscapes.github.io/approach-guide
  repo-url: https://github.com/openscapes/approach-guide
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer: "Openscapes Core Team, Julia Stewart Lowndes & Erin Robinson (2021). Openscapes Approach Guide (Version v0.0.1)."
  
  navbar: 
    background: light
    right: 
      - sidebar:menu
      - icon: github
        href: https://github.com/openscapes/approach-guide
        
  sidebar:   
    - id: menu
      title: "Menu"
      logo: images/openscapes_hex.png
      style: "docked"
      collapse-level: 1
      align: left
      contents:
        - section: "Welcome"
          contents:
            - index.qmd
        - section: "Openscapes Approach"
          contents:  
            - approach/index.md
            - approach/code-of-conduct.md
            - approach/seaside-chats.md
            - approach/onboarding.md
            - approach/tooling.md
            - approach/partners.md
            - approach/calendar.md
        - section: "Champions Program"
          contents:
            - champions/index.qmd
            - champions/design.md
            - champions/timeline.md
            - champions/pre-cohort-engage.md
            - champions/pre-cohort-tech.qmd
            - champions/lessons.qmd
            - champions/leading-cohort-calls.qmd
            - champions/post-cohort-followup.md
        - section: "Contributing"
          contents:
            - contributing/index.md
            - contributing/setup.md
            - contributing/workflow.md
            - contributing/inspiration.md

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true 
    
filters:
  - include-files.lua
  - quarto    
