project:
  type: site
  output-dir: _site

execute:
  ipynb: false
  freeze: true
  
site:
  site-url: https://openscapes.github.io/approach-guide
  repo-url: https://github.com/openscapes/approach-guide
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    title: "Openscapes Approach Guide"
    logo: openscapes_hex.png
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    align: left
    tools:
      - icon: github
        href: https://github.com/openscapes/approach-guide
    contents:
      - text: "Welcome"
        href: index.md
      - section: practices/index.md
        contents:  
        - practices/code-of-conduct.md
      - section: champions/index.qmd
        contents:
        - champions/timeline.md
        - champions/plan.md
        - champions/engage.md
        - champions/deliver.md
      - section: "Reference"
        contents:
        - reference/inspiration.md

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true 
    
