project:
  type: site
  output-dir: _site

execute:
  ipynb: false
  freeze: true
  
site:
  site-url: https://openscapes.github.io/approach-guide
  repo-url: https://github.com/openscapes/approach-guide
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    title: "Approach Guide"
    logo: images/openscapes_hex.png
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    align: left
    tools:
      - icon: github
        href: https://github.com/openscapes/approach-guide
    contents:
      - text: "Welcome"
        href: index.md
      - section: approach/index.qmd
        contents:  
        - approach/code-of-conduct.md
        - approach/seaside-chats.md
        - approach/onboarding.md
        - approach/tooling.md
        - approach/partners.md
      - section: champions/index.qmd
        contents:
        - champions/design.md
        - champions/timeline.md
        - champions/pre-cohort-engage.md
        - champions/pre-cohort-tech.md
        - champions/lessons.qmd
        - champions/leading.md
        - champions/followup.md
      - section: contributing/index.md
        contents:
        - contributing/setup.md
        - contributing/workflow.md
        - contributing/inspiration.md
    footer:
      - attribution:"For attribution, please cite this work as Openscapes Approach Guide. Retrieved from https://github.com/Openscapes/approach-guide "

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true 
    
